<a href="https://colab.research.google.com/github/Zhuchkovdv/Python/blob/main/Linalg_6_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Жучков Дмитрий DS_med_1530

In [ ]:
import math
import numpy as np
from numpy.linalg import norm
import scipy.linalg

# __6.2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

In [ ]:
x = [3, -1, 1]
y = [2, -5, -3]
z = [1, 1, -1]
b = [4, -17, 0]
A = np.array([x, y, z])
A_= np.column_stack([A, b])
r = np.linalg.matrix_rank(A)
r_ = np.linalg.matrix_rank(A_)
print(f'Число переменных:\n{len(x)}')
print(f'Число уравнений:\n{len(b)}')
print(f'Матрица коэффициентов:\n{A}')
print(f'Ранг матрицы коэффициентов:\n{r}')
print(f'Расширенная матрица:\n{A_}')
print(f'Ранг расширенной матрицы:\n{r_}')
print()
if r < r_:
    print(f'Система несовместна')
if r == r_:
    if len(b) == len(x):
        print(f'Система совместна, определенна и имеет единственное решение')
    else:
        print(f'Система совместна, но неопределенна и имеет бесконечное множество решений')

Число переменных:
3
Число уравнений:
3
Матрица коэффициентов:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Ранг матрицы коэффициентов:
3
Расширенная матрица:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг расширенной матрицы:
3

Система совместна, определенна и имеет единственное решение


б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [ ]:
x = [2, -4, 6]
y = [1, -2, 3]
z = [3, -6, 9]
b = [1, -2, 5]
A = np.array([x, y, z])
A_= np.column_stack([A, b])
r = np.linalg.matrix_rank(A)
r_ = np.linalg.matrix_rank(A_)
print(f'Число переменных:\n{len(x)}')
print(f'Число уравнений:\n{len(b)}')
print(f'Матрица коэффициентов:\n{A}')
print(f'Ранг матрицы коэффициентов:\n{r}')
print(f'Расширенная матрица:\n{A_}')
print(f'Ранг расширенной матрицы:\n{r_}')
print()
if r < r_:
    print(f'Система несовместна')
if r == r_:
    if len(b) == len(x):
        print(f'Система совместна, определенна и имеет единственное решение')
    else:
        print(f'Система совместна, но неопределенна и имеет бесконечное множество решений')

Число переменных:
3
Число уравнений:
3
Матрица коэффициентов:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Ранг матрицы коэффициентов:
1
Расширенная матрица:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг расширенной матрицы:
2

Система несовместна


в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [ ]:
x = [1, 2, 5]
y = [3, 1, -8]

b = [4, -2]
A = np.array([x, y])
A_= np.column_stack([A, b])
r = np.linalg.matrix_rank(A)
r_ = np.linalg.matrix_rank(A_)
print(f'Число переменных:\n{len(x)}')
print(f'Число уравнений:\n{len(b)}')
print(f'Матрица коэффициентов:\n{A}')
print(f'Ранг матрицы коэффициентов:\n{r}')
print(f'Расширенная матрица:\n{A_}')
print(f'Ранг расширенной матрицы:\n{r_}')
print()
if r < r_:
    print(f'Система несовместна')
if r == r_:
    if len(b) == len(x):
        print(f'Система совместна, определенна и имеет единственное решение')
    else:
        print(f'Система совместна, но неопределенна и имеет бесконечное множество решений')

Число переменных:
3
Число уравнений:
2
Матрица коэффициентов:
[[ 1  2  5]
 [ 3  1 -8]]
Ранг матрицы коэффициентов:
2
Расширенная матрица:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг расширенной матрицы:
2

Система совместна, но неопределенна и имеет бесконечное множество решений


#__6.3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [ ]:
x = [1, 3, -2, 4]
y = [0, 5, 0, 1]
z = [0, 0, 3, 0]
w = [0, 0, 0, 2]

b = [3, 2, 4, 1]
A = np.array([x, y, z, w])
A_= np.column_stack([A, b])
r = np.linalg.matrix_rank(A)
r_ = np.linalg.matrix_rank(A_)
print(f'Число переменных:\n{len(x)}')
print(f'Число уравнений:\n{len(b)}')
print(f'Матрица коэффициентов:\n{A}')
print(f'Ранг матрицы коэффициентов:\n{r}')
print(f'Расширенная матрица:\n{A_}')
print(f'Ранг расширенной матрицы:\n{r_}')
print()
if r < r_:
    print(f'Система несовместна')
if r == r_:
    if r == len(x):
        print(f'Система совместна, определенна и имеет единственное решение')
    else:
        print(f'Система совместна, но неопределенна и имеет бесконечное множество решений')

Число переменных:
4
Число уравнений:
4
Матрица коэффициентов:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Ранг матрицы коэффициентов:
4
Расширенная матрица:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг расширенной матрицы:
4

Система совместна, определенна и имеет единственное решение


#__7.1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$   
 

In [ ]:
x = [1, -2]
y = [3, -4]
b = [1, 7]
A = np.array([x, y])
A_ = np.column_stack([A, b])
D = np.linalg.det(A)
D1 = np.linalg.det(A_[:, [2, 1]])
D2 = np.linalg.det(A_[:, [0, 2]])
print(f'Матрица коэффициентов:\n{A}')
print(f'Расширенная матрица:\n{A_}')
print(D, D1, D2)
print()
print(f'x1 = {D1/D :.0f}, x2 = {D2/D :.0f}')

Матрица коэффициентов:
[[ 1 -2]
 [ 3 -4]]
Расширенная матрица:
[[ 1 -2  1]
 [ 3 -4  7]]
2.0000000000000004 9.999999999999998 3.999999999999999

x1 = 5, x2 = 2


  б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [ ]:
x = [2, -1, 5]
y = [1, 1, -3]
z = [2, 4, 1]
b = [10, -2, 1]
A = np.array([x, y, z])
D = np.linalg.det(A)
A_ = np.column_stack([A, b])
D1 = np.linalg.det(A_[:, [3, 1, 2]])
D2 = np.linalg.det(A_[:, [0,3, 2]])
D3 = np.linalg.det(A_[:, [0, 1, 3]])
print(f'Матрица коэффициентов:\n{A}')
print(f'Расширенная матрица:\n{A_}')
print(D, D1, D2, D3)
print()
print(f'x1 = {D1/D :.0f}, x2 = {D2/D :.0f}, x3 = {D3/D :.0f}')

Матрица коэффициентов:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Расширенная матрица:
[[ 2 -1  5 10]
 [ 1  1 -3 -2]
 [ 2  4  1  1]]
42.99999999999998 86.00000000000004 -43.000000000000014 42.99999999999998

x1 = 2, x2 = -1, x3 = 1


# Не совсем задание __7.5.*__, но Крамер тоже работает))

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$


In [ ]:
x = [2, 1, 3]
y = [11, 7, 5]
z = [9, 8, 4]
b = [1, -6, -5]
A = np.array([x, y, z])
D = np.linalg.det(A)
A_ = np.column_stack([A, b])
D1 = np.linalg.det(A_[:, [3, 1, 2]])
D2 = np.linalg.det(A_[:, [0,3, 2]])
D3 = np.linalg.det(A_[:, [0, 1, 3]])
print(f'Матрица коэффициентов:\n{A}')
print(f'Расширенная матрица:\n{A_}')
A_= np.column_stack([A, b])
r = np.linalg.matrix_rank(A)
r_ = np.linalg.matrix_rank(A_)
print(f'Число переменных:\n{len(x)}')
print(f'Число уравнений:\n{len(b)}')
print(f'Ранг матрицы коэффициентов:\n{r}')
print(f'Ранг расширенной матрицы:\n{r_}')
print()
if r < r_:
    print(f'Система несовместна')
if r == r_:
    if len(b) == len(x):
        print(f'Система совместна, определенна и имеет единственное решение')
    else:
        print(f'Система совместна, но неопределенна и имеет бесконечное множество решений')
print()
print(D, D1, D2, D3)
print()
print(f'x1 = {D1/D :.0f}, x2 = {D2/D :.0f}, x3 = {D3/D :.0f}')

Матрица коэффициентов:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]
Расширенная матрица:
[[ 2  1  3  1]
 [11  7  5 -6]
 [ 9  8  4 -5]]
Число переменных:
3
Число уравнений:
3
Ранг матрицы коэффициентов:
3
Ранг расширенной матрицы:
3

Система совместна, определенна и имеет единственное решение

52.00000000000001 -51.999999999999986 0.0 52.00000000000001

x1 = -1, x2 = 0, x3 = 1


$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [ ]:
x = [81, -45, 45]
y = [-45, 50, -15]
z = [45, -15, 38]
b = [531, -460, 193]
A = np.array([x, y, z])
D = np.linalg.det(A)
A_ = np.column_stack([A, b])
D1 = np.linalg.det(A_[:, [3, 1, 2]])
D2 = np.linalg.det(A_[:, [0,3, 2]])
D3 = np.linalg.det(A_[:, [0, 1, 3]])
print(f'Матрица коэффициентов:\n{A}')
print(f'Расширенная матрица:\n{A_}')
A_= np.column_stack([A, b])
r = np.linalg.matrix_rank(A)
r_ = np.linalg.matrix_rank(A_)
print(f'Число переменных:\n{len(x)}')
print(f'Число уравнений:\n{len(b)}')
print(f'Ранг матрицы коэффициентов:\n{r}')
print(f'Ранг расширенной матрицы:\n{r_}')
print()
if r < r_:
    print(f'Система несовместна')
if r == r_:
    if len(b) == len(x):
        print(f'Система совместна, определенна и имеет единственное решение')
    else:
        print(f'Система совместна, но неопределенна и имеет бесконечное множество решений')
print()
print(D, D1, D2, D3)
print()
print(f'x1 = {D1/D :.0f}, x2 = {D2/D :.0f}, x3 = {D3/D :.0f}')

Матрица коэффициентов:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]
Расширенная матрица:
[[  81  -45   45  531]
 [ -45   50  -15 -460]
 [  45  -15   38  193]]
Число переменных:
3
Число уравнений:
3
Ранг матрицы коэффициентов:
3
Ранг расширенной матрицы:
3

Система совместна, определенна и имеет единственное решение

18225.000000000007 109350.00000000017 -91124.99999999996 -72899.99999999991

x1 = 6, x2 = -5, x3 = -4
