<a href="https://colab.research.google.com/github/Zhuchkovdv/Python/blob/main/Linalg_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Жучков Дмитрий DS_med_1530

In [ ]:
import math
import numpy as np
from numpy.linalg import norm
import scipy.linalg
np.set_printoptions(precision=2, suppress=True)

# 1. Найти с помощью NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}$$


In [ ]:
x = [1, 2, 0]
y = [0, 0, 5]
z = [3, -4, 2]
w = [1, 6, 5]
u = [0, 1, 0]

A = np.array([x, y, z, w, u])
print(f'Матрица:\n{A}')

Матрица:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [ ]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [ ]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [ ]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [ ]:
print(np.dot(U.T, U))

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [ ]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [ ]:
print(np.dot(V.T, V))

[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


In [ ]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


# 2. Для матрицы из предыдущего задания найти:

а) евклидову норму;
    
б) норму Фробениуса.

In [ ]:
print(f'Евклидова норма A:\n{norm(A, ord=2)}')

Евклидова норма A:
8.824868854820444


In [ ]:
print(f'Евклидова норма A:\n{D[0, 0]}')

Евклидова норма A:
8.824868854820442


In [ ]:
print(f'Норма Фробениуса D:\n{np.linalg.norm(D)}')

Норма Фробениуса D:
11.04536101718726


In [ ]:
print(f'Норма Фробениуса A:\n{np.linalg.norm(A)}')

Норма Фробениуса A:
11.045361017187261


In [ ]:
pow_mas = (D[:])**2
print(f'Норма Фробениуса D:\n{np.sqrt(pow_mas.sum())}')

Норма Фробениуса D:
11.045361017187261


In [ ]:
pow_mas = (A[:])**2
print(f'Норма Фробениуса A:\n{np.sqrt(pow_mas.sum())}')

Норма Фробениуса A:
11.045361017187261


In [ ]:
highCountX = 2
lowValY = 3.
D_ = np.asarray(D)
low_values_flags = D_ < lowValY  
D_[low_values_flags] = 0

In [ ]:
print(f'Матрица D_:\n{D_}')

Матрица D_:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   0.  ]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [ ]:
print(f'Матрица A_:\n{np.dot(np.dot(U, D_), V.T)}')

Матрица A_:
[[-0.25  1.72  0.42]
 [ 1.44  0.32  4.52]
 [ 1.77 -4.28  2.41]
 [ 0.42  5.87  5.19]
 [-0.19  0.96  0.06]]


In [ ]:
print(f'Норма Фробениуса A_:\n{np.linalg.norm(np.dot(np.dot(U, D_), V.T))}')

Норма Фробениуса A_:
10.751062891895108


In [ ]:
print(f'Норма Фробениуса D_:\n{np.linalg.norm(D_)}')

Норма Фробениуса D_:
10.751062891895108
